//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleaMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Favorite = new HashSet<Favorite>();
            this.TradeRecord = new HashSet<TradeRecord>();
        }
    
        public int ProID { get; set; }
        public string ProName { get; set; }
        public Nullable<int> ProLevel { get; set; }
        public decimal ProOldPrice { get; set; }
        public Nullable<decimal> ProNewPrice { get; set; }
        public int ProCateg { get; set; }
        public int ProWhoUser { get; set; }
        public string ProIntro { get; set; }
        public string ProImgUrl { get; set; }
        public Nullable<System.DateTime> ProReleaseTime { get; set; }
        public bool ProIsSell { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Favorite> Favorite { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<TradeRecord> TradeRecord { get; set; }
    }
}
