//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleaMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRole
    {
        public SRole()
        {
            this.Administrators = new HashSet<Administrators>();
            this.Users = new HashSet<Users>();
        }
    
        public int RoleID { get; set; }
        public string RoleType { get; set; }
    
        public virtual ICollection<Administrators> Administrators { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
