//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleaMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Favorite = new HashSet<Favorite>();
            this.Product = new HashSet<Product>();
            this.TradeRecord = new HashSet<TradeRecord>();
            this.TradeRecord1 = new HashSet<TradeRecord>();
        }
    
        public int UserID { get; set; }
        public string UserAccount { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public string UserGender { get; set; }
        public string UserAddress { get; set; }
        public string UserIntro { get; set; }
        public string UserPhone { get; set; }
        public Nullable<byte> UserStatus { get; set; }
        public int UserRole { get; set; }
        public string UserIcon { get; set; }
        public string UserQQ { get; set; }
    
        public virtual ICollection<Favorite> Favorite { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual SRole SRole { get; set; }
        public virtual ICollection<TradeRecord> TradeRecord { get; set; }
        public virtual ICollection<TradeRecord> TradeRecord1 { get; set; }
    }
}
